- name: 复制flanneld到所有node节点
  unarchive: src=../files/flanneld.tar.gz dest=/opt/ mode=500

- name: 配置systemd文件
  template: src=../template/flanneld.service.j2 dest=/etc/systemd/system/flanneld.service

- name: reload systemd
  command: systemctl daemon-reload

- name: start flannled
  systemd: name=flanneld state=started enabled=yes
