---
- hosts: etcd
  gather_facts: true
  roles:
  - etcd

- hosts: etcd[0]
  tasks:
  - command: /opt/etcd/etcdctl set '/kubernetes/network/config' '{"Network":"172.17.0.0/16"}'

- hosts: node
  gather_facts: true
  roles:
  - common    
  - flanneld
  - docker



