---
- hosts: all
  roles:
  #- common

- hosts: etcd
  gather_facts: true
  roles:
  #- etcd

- hosts: etcd[0]
  tasks:
  #- command: /opt/etcd/etcdctl set '/kubernetes/network/config' '{"Network":"172.17.0.0/16"}'

- hosts: node
  gather_facts: true
  roles:
  # - kubectl
  # - kube-apiserver
  # - kube-controller-manager
  #  - kube-scheduler
  tasks:
    - name: 将master的证书和配置文件分发到node上
      synchronize:
        src: /root/test
        dest: /root/test
        mode: push
      delegate_to: 172.31.211.138

- hosts: node
  gather_facts: true
  roles:
  #- flanneld
  #- docker



