
- unarchive: src=../files/kubernetes.tar.gz dest=/opt/

- template: src=../template/kubelet.config.json.j2 dest=/etc/kubernetes/ssl/kubelet.config.json

- file: path=/var/lib/kubelet state=directory

- copy: src=../files/kubelet.service dest=/etc/systemd/system/

- name: reload systemd
  command: systemctl daemon-reload

- name: start flannled
  systemd: name=kubelet state=started enabled=yes
