
- unarchive: src=../files/kubernetes.tar.gz dest=/opt/

- template: src=../template/kubelet.config.json.j2 dest=/etc/systemd/system/kubelet.config.json

- name: reload systemd
  command: systemctl daemon-reload

- name: start flannled
  systemd: name=kubelet state=started enabled=yes