- file: path=/ilabservice/etcd state=directory 
- file: path=/etc/etcd state=directory 
- copy: src=../files/etcd.conf dest=/etc/etcd/
- copy: src=../files/etcd dest=/ilabservice/etcd/  mode=500
- copy: src=../files/etcdctl dest=/ilabservice/etcd/ mode=500
- template: src=../template/etcd.service.j2 dest=/etc/systemd/system/etcd.service 
- command: systemctl daemon-reload
- systemd: name=etcd state=started enabled=yes

  