- file: path=/opt/etcd state=directory 
- file: path=/etc/etcd state=directory 
- copy: src=etcd.conf dest=/etc/etcd/
- copy: src=etcd dest=/opt/etcd/  mode=500
- copy: src=etcdctl dest=/opt/etcd/ mode=500
- template: src=etcd.service.j2 dest=/etc/systemd/system/etcd.service 
- command: systemctl daemon-reload
- systemd: name=etcd state=started enabled=yes
  