- name: 安装基础软件包
  yum: 
    name:
    - epel-release
    - rsync
    - conntrack 
    - ipvsadm 
    - ipset 
    - jq
    - sysstat 
    - curl
    - iptables
    - libseccomp
    state: latest

- name: 关闭防火墙
  service: name=firewalld state=stopped enabled=no

- name: 关闭selinux
  lineinfile:
    dest: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=disabled'

- name: 关闭交换区
  command: swapoff -a

- name: 加载netfilter模块
  command: modprobe br_netfilter
- command: modprobe ip_vs


- copy: src=kubernetes.conf dest=/etc/sysctl.d/
- command: sysctl -p /etc/sysctl.d/kubernetes.conf

- name: 设置时区
  command: timedatectl set-timezone Asia/Shanghai
- command: timedatectl set-local-rtc 0
- systemd: name=rsyslog state=restarted
- systemd: name=crond state=restarted

- file: path=/etc/kubernetes/ssl state=directory
