- unarchive: src=docker.tar.gz dest=/opt/ mode=500

- copy: src=docker.service dest=/etc/systemd/system/

- file: path=/etc/docker state=directory 

- copy: src=daemon.json dest=/etc/docker/

- file: src=/opt/docker/docker dest=/usr/bin/docker state=link

- name: reload systemd
  command: systemctl daemon-reload

- name: start docker
  systemd: name=docker state=started enabled=yes
