- unarchive: src=kubernetes.tar.gz dest=/opt/

- template: src=kube-scheduler.service.j2 dest=/etc/systemd/system/kube-scheduler.service

- command: systemctl daemon-reload 

- systemd: name=kube-scheduler state=started enabled=yes

