- unarchive: src=../files/kubernetes.tar.gz dest=/opt/

- template: src=../template/kube-controller-manager.service.j2 dest=/etc/systemd/system/kube-controller-manager.service

- command: systemctl daemon-reload 

- systemd: name=kube-controller-manager state=started enabled=yes

